### ISSUE TITLE
SUGGESTION: Add PHP (Hypertext Preprocessor) to AIO Egg for web applications 

### ISSUE THREAD

**Issue by Echo-Script** [DanBot-Hosting/pterodactyl-eggs#1]

**Comment by NWJ9PB** [comment]
Bump!

**Comment by AndyIsHereBoi** [comment]
bump

**Comment by omsenjalia** [comment]
Nginx exists for a reason

**Comment by AndyIsHereBoi** [comment]
not for pterodactyl

**Comment by AndyIsHereBoi** [comment]
maybe u can run nginx in a docker container but idk

**Comment by danielpmc** [comment]
Nginx is already a hosting option at DBH. However i will look at adding it into the AIO egg too.

**Comment by ririko5834** [comment]
Nginx or caddy could be added to aio

**Comment by danielpmc** [comment]
@DIBSTERYT

**Comment by DEV-DIBSTER** [comment]
Might be possible, looking into it, my only concern is that we might be adding too many things to the all in one egg. Yes it's a all in one, but does it need to have every possible type?

**Comment by DEV-DIBSTER** [comment]
Staff discussion, we have voted against such a decision for the current state of the egg.

**Comment by ririko5834** [comment]
It wasnt completed

**Comment by DEV-DIBSTER** [comment]
> It wasnt completed

Yeah we're not going to add it.
