### ISSUE TITLE
Change language version

### ISSUE THREAD

**Issue by ririko5834** [DanBot-Hosting/pterodactyl-eggs#13]
There should be guide or script to change nodejs, python, etc. version.

**Comment by ririko5834** [comment]
I tried to change nodejs version but it isnt possible, root is missing.

![image](https://user-images.githubusercontent.com/64729293/192225151-eb48f05a-b09f-46d6-9b60-12ebcb591eac.png)

**Comment by djohts** [comment]
use nvm

**Comment by ririko5834** [comment]
Tell exactly how

**Comment by djohts** [comment]
![image](https://user-images.githubusercontent.com/68508885/192267893-35d24b4c-6be4-40c5-9597-cfde696c104c.png)

**Comment by djohts** [comment]
to install it just google how to do so, it should work. tested.

**Comment by DEV-DIBSTER** [comment]
For NodeJS you can change it with nvm.

For python you have python which is 2.7.16, python 3 which is 3.7.3, and python 3.10.0

Others you can't change versions iirc.

**Comment by ririko5834** [comment]
> ![image](https://user-images.githubusercontent.com/68508885/192267893-35d24b4c-6be4-40c5-9597-cfde696c104c.png)

Its for vps, not docker container with this egg, there isn't nvm
`bash: nvm: command not found`

**Comment by djohts** [comment]
> > *hidden*
> 
> Its for vps, not docker container with this egg, there isn't nvm `bash: nvm: command not found`

because you need to install it?

**Comment by DEV-DIBSTER** [comment]
You curl it's source code, run a couple commands and have it installed on your docker server.

**Comment by djohts** [comment]
> You curl it's source code, run a couple commands and have it installed on your docker server.

actually you can run just 2 commands. `curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash `

**Comment by Darker-Ink** [comment]
Note This only works on the AIO egg

1) Run `curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash`
2) Make a new file called `.bashrc`
3) Add ```export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm``` to the file
4) restart the server
5) use `nvm install <version>`

Boom you should now have nvm and a custom Nodejs Version installed.

Every time you restart the server you will have to do `nvm use <version>`
