### ISSUE TITLE
Aio egg error 

### ISSUE THREAD

**Issue by VR2211** [DanBot-Hosting/pterodactyl-eggs#31]
Good day

Every time try the server finish installing but it does not come out of installing and I get an error on admin panel "**This server is in a failed install state and cannot be recovered. Please delete and re-create the server.**"

please help I change nother at all

Thank you

**Comment by VR2211** [comment]
I also always get the email Server is installed but it not working

**Comment by djohts** [comment]
are you trying to use aio egg on an arm cpu? if so, then change install script container image to `alpine:3.16`:
![image](https://github.com/DanBot-Hosting/pterodactyl-eggs/assets/68508885/521f843e-9d20-4107-949a-b86ca22c9308)

**Comment by VR2211** [comment]
> are you trying to use aio egg on an arm cpu? if so, then change install script container image to `alpine:3.16`:
> ![image](https://github.com/DanBot-Hosting/pterodactyl-eggs/assets/68508885/521f843e-9d20-4107-949a-b86ca22c9308)
> 

I bevaile so thank you I will try and get back to you.
