### ISSUE TITLE
Versions in aio egg

### ISSUE THREAD

**Issue by ririko5834** [DanBot-Hosting/pterodactyl-eggs#8]
Add some interactive prompt to choose which language (nodejs, python, golang, java, ...) do you want to install and also prompt for the version. This prompt should be asked in first server start, so users can pick programming language and version of it.

**Comment by cyanide1x** [comment]
uhhh no. nobody wants that. We want something based off a shell. Not our fault you don't have basic linux knowledge.

**Comment by cyanide1x** [comment]
and quit making fucking issues for your suggestions

**Comment by ririko5834** [comment]
So write guide how to change nodejs, python version using commands

**Comment by ghost** [comment]
ahh it not DBH problem it your issue just search google or any search engine you use it not hard

**Comment by vinc3nz** [comment]
I may write a little guide for this soon. Maybe even a small batch script for changing nodejs/java/python. But also: How can you host a bot if you can't change this? It literly is just googling/binging/duckduckgoing.

**Comment by djohts** [comment]
> I may write a little guide for this soon. Maybe even a small batch script for changing nodejs/java/python. But also: How can you host a bot if you can't change this? It literly is just googling/binging/duckduckgoing. 

who uses bing :kek:
